apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "persistent-volume-ebs"
  labels:
    name: pv-ebs 
spec:
  capacity:
    storage: "10Gi" 
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore: 
    fsType: "ext4"
    volumeID: $(EBS_VOLUME_ID)