apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  selector:
    matchLabels:
      name: pv-ebs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi